@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}
@url = http://{{host}}/api
@authKey = abcd


### missing authKey and action : => HTTP/1.1 401 Unauthorized
GET {{url}}/index.php

### missing action invalid authKey  : => HTTP/1.1 401 Unauthorized
GET {{url}}/index.php
x-authKey: INVALID

### missing action : HTTP/1.1 500 Internal Server Error
GET {{url}}/index.php
x-authKey: {{authKey}}

### info action => 200 OK JSON
GET {{url}}/index.php?action=info


### ping action => 200 OK 'pong'
GET {{url}}/index.php?action=ping


### send-sms action (silent mode ON) => HTTP/1.1 200 OK
GET {{url}}/index.php?action=send-sms
    &silent=true
    &msg=the%20message
x-authKey: {{authKey}}

### send-sms action (silent mode ON) - default message => HTTP/1.1 200 OK
GET {{url}}/index.php?action=send-sms
    &silent=true
x-authKey: {{authKey}}

### send-sms action (silent mode ON) - custom message => HTTP/1.1 200 OK
GET {{url}}/index.php?action=send-sms
    &silent=true
    &msg=hello%20world
x-authKey: {{authKey}}

### send-sms action (silent mode OFF)
GET {{url}}/index.php?action=send-sms
    &msg=hello%20world
x-authKey: {{authKey}}

### log action

GET {{url}}/index.php?action=log
x-authKey: {{authKey}}

### health check

GET {{url}}/index.php?action=health-check
x-authKey: {{authKey}}

### FTP: ls - default
GET {{url}}/index.php?action=ls
x-authKey: {{authKey}}

### FTP: ls - folder exists

GET {{url}}/index.php?action=ls&dir=cam1/2025/11/29
x-authKey: {{authKey}}

### FTP: ls - folder Not found

GET {{url}}/index.php?action=ls&dir=NOT_FOUND
x-authKey: {{authKey}}
### FTP: ls - folder Not found

GET {{url}}/index.php?action=ls&dir=../..
x-authKey: {{authKey}}

